version: '3.7'

services:
  api:
    container_name: "${START_APP_NAME}_api"
    env_file: ./.env
    ports:
      - ${START_APP_PORT}:${START_APP_PORT}
    build:
      context: ./
      dockerfile: docker-compose/node-serve/node.dockerfile
    volumes:
      - ~/.ssh:/home/.ssh
      - ./:/usr/src/api
      - node_modules:/usr/src/api/node_modules
    networks:
      - ${START_APP_NETWORK}

  # Mailing Server
  mailhog:
    image: mailhog/mailhog
    container_name: "${START_APP_NAME}_mailhog"
    logging:
      driver: 'none'
    ports:
      - ${START_MAILHOG_WEB_PORT}:${START_MAILHOG_WEB_PORT}
      - ${START_MAILHOG_SMTP_RECEIVE_PORT}:${START_MAILHOG_SMTP_RECEIVE_PORT}
      - ${START_MAILHOG_INTERFACE_PORT}:${START_MAILHOG_INTERFACE_PORT}
    networks:
        - ${START_APP_NETWORK}

volumes:
  node_modules:

# Define networks
networks:
  backend-nestjs-jaidenmeiden:
    driver: bridge
